### ISSUE TITLE
Create the remote-deploy folder if it is missing or was deleted.

### ISSUE THREAD

**Issue by johnnyman727** [tessel/v2-cli#24]
Currently, if the `/tmp/remote-script` folder is non-existant, the CLI will throw an error:
```
INFO Deploying code of size 23468 bytes ...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at writeAfterEnd (_stream_writable.js:167:12)
    at Channel.Writable.write (_stream_writable.js:214:5)
    at Channel.Writable.end (_stream_writable.js:449:10)
    at /Users/Jon/Work/technical/prime-cli/lib/deploy.js:34:16
    at Parse.<anonymous> (/Users/Jon/Work/technical/cli/src/bundle.js:179:7)
    at Parse.emit (events.js:104:17)
    at Parse._streamEnd (/Users/Jon/Work/technical/cli/node_modules/tar/lib/parse.js:65:6)
    at BlockStream.<anonymous> (/Users/Jon/Work/technical/cli/node_modules/tar/lib/parse.js:51:8)
    at BlockStream.emit (events.js:104:17)
    at BlockStream._emitChunk (/Users/Jon/Work/technical/cli/node_modules/tar/node_modules/block-stream/block-stream.js:203:10)
```

**Comment by johnnyman727** [comment]
Fixed by #27.
